### ISSUE TITLE
Handle spaces in the directory path for `vagrant global-status`

### ISSUE THREAD

**Issue by ChetanKoneru** [p3r7/magrant#2]
I have a project in 
![image](https://user-images.githubusercontent.com/23665525/124398307-a8542480-dcda-11eb-8606-897cc32712a6.png)

The project is behind a symlink, `vagrant global-status` give absolute path.

![image](https://user-images.githubusercontent.com/23665525/124398321-c02ba880-dcda-11eb-80c0-c7ed9f533daa.png)

while `magrant machine` does not capture absolute path due to `spaces`

![image](https://user-images.githubusercontent.com/23665525/124398365-fb2ddc00-dcda-11eb-83b7-49d6015cb632.png)

**Comment by p3r7** [comment]
Good catch.

Thankfully the path is the last element in the line, which prevented me from having to use conditionals.

Last commit should fix it.

Could you test again?

**Comment by ChetanKoneru** [comment]
![image](https://user-images.githubusercontent.com/23665525/124609389-32180500-de35-11eb-930d-015857fe740c.png)

I think `tabulated-list` shifted now.

error now - `with-shell-interpreter--generate-props: Path running doesn’t seem to exist`

**Comment by p3r7** [comment]
Ah, crap, had to do w/ the output of `vagrant global-status` using sometimes more than 1 space as a delimiter.

Thankfully, `s-split-up-to` support a regexp as its delimiter arg.

6309c001355126e3ade79493479b517925943d17 should fix it. It might take a 1 or 2 hours for melpa to rebuild and make it available.

**Comment by ChetanKoneru** [comment]
Awesome, works now. Thanks for the quick fix.

**Comment by ChetanKoneru** [comment]
@p3r7 Can you also support `tramp` with `ssh`?
similar to this - https://github.com/abrochard/kubel/blob/801d4cc78cb59b3c39e9ea53d7f16ec3c9a6bb6b/kubel.el#L836

right now I was able to `tramp` into `vagrant machine` by coping the contents of `vagrant ssh-config` to `~/.ssh/config`.

**Comment by p3r7** [comment]
Have you tried [vagrant-tramp](https://github.com/dougm/vagrant-tramp)?

I don't use it personally, as I systematically provision all my VMs w/ ansible, for which I have playbooks to deploy my main SSH key. Ans I use a (yet to be released) [ansible inventory backed helm command](https://github.com/p3r7/emacs.d/blob/master/plugins/ansible-tramp/ansible-tramp.el) to quickly access all of my VMs/machines whatever/wherever they are. 

An integration via a transient key, as an alternative to `b` +  `b` could be nice though, I guess, for dir tracking mainly.

**Comment by ChetanKoneru** [comment]
`vagrant-tramp` is buggy, was not able to set it up. The reason I use `tramp` is that I do not have to install a editor in the `VM`. With `tramp` I could just open my files in `Emacs`. That is the only reason I prefer it.

Yes, I have been using `b` `b` to ssh in to the `machine`.

Yes, `ansible-tramp` looks great. I think that package can be used here with little changes.

**Comment by p3r7** [comment]
> The reason I use `tramp` is that I do not have to install a editor in the `VM`.

100%.

> `vagrant-tramp` is buggy, was not able to set it up. 

I'll give it a try and see how it behaves.

> right now I was able to tramp into vagrant machine by coping the contents of `vagrant ssh-config` to `~/.ssh/config`.

If I can't enable dirtracking w/ `vagrant ssh` (what vagrant-tramp uses), `vagrant ssh-config` seems like a promising alternative.
I could make a command that stores this into a temporary file and use the `-i` argument of SSH to point to it (I [toyed w/ the idea](https://www.eigenbahn.com/2020/01/15/tramp-autologin-insanity) in the past).

**Comment by ChetanKoneru** [comment]
>I could make a command that stores this into a temporary file and use the -i argument of SSH to point to it (I toyed w/ the idea in the past).

love this idea.

here is a reference to create temp file - https://stackoverflow.com/a/23685489/16319013
